# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2016

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Tags: /tags
  Archives: /archives/
  Links : /links
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Cobalt Blue
  toc: true
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: true
  qrCode:
    wechat: /image/reward/wechat.png
  # alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: 168@yifans.com
  stack-overflow: https://stackoverflow.com/users/5958443/yifan-zhao
  twitter: https://twitter.com/zhaoyifans
  facebook:
  linkedin:
  google:
  github: https://github.com/imzyf
  weibo: https://weibo.com/zhaoyifans
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: er5hlK0M8mWKUTrVtqnHl97N-gzGzoHsz
  app_key: a6lIOEoJs3ijGvj3eP2rkFGG

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname: yifans

#Changyan
changyan:
  appid:
  appkey:

# ===========================================
# Version
# ===========================================
version: 2.6.0
